### PR TITLE
Remove unneeded code

### PR DESCRIPTION
**Pull request by schriftgestalt**

### CODE REVIEW

**Comment by LettError** [comment]
I've done some more work on the color components. If you remove `cmd_exportCurrentFont.py` from this PR I can add the others.

**Comment by schriftgestalt** [comment]
I updated the code.

**Comment by LettError** [comment]
Thanks, that all seems to work. Does this require further work for the glyphs plugin or is that automatic?

**Comment by schriftgestalt** [comment]
I did look into copying the core code files into the plugin like it is done with the extension. But there are slight differences with the imports. But that could be solved by conditionally import to be able to use the same code for both platforms. I can do that.

**Pull request merged**
